server:
  port: "8080"
  host: "localhost"

static:
  folder: "/app/example_root/image_root/unverlify"

database:
  host: ""
  port: ""
  username: ""
  password: ""
  database: ""

logging:
  level: "debug"
  format: "console"

cors:
  allowed_origins: ["http://localhost:3000", "http://frontend:3000"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["*"]