server:
  port: "8080"
  host: "localhost"

static:
  root_folder: "../example_root/image_root/unverlify"
  backup_folder: "../backups"


database:
  host: ""
  port: ""
  username: ""
  password: ""
  database: ""

logging:
  level: "debug"
  format: "console"

cors:
  allowed_origins: ["http://localhost:3000", "http://localhost:3001"]
  allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allowed_headers: ["*"] 