info:
  contact: {}
paths:
  /api/getAllPages:
    get:
      description: Returns all page details for a given job
      parameters:
      - description: Job name
        in: query
        name: job
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all pages for a job
      tags:
      - pages
  /api/getBase64Image:
    get:
      description: Returns a base64 encoded image for a specific image path in a job
      parameters:
      - description: Job name
        in: query
        name: job
        required: true
        type: string
      - description: Image path
        in: query
        name: imagePath
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get base64 image by image path
      tags:
      - images
  /api/getBase64ImageSet:
    get:
      description: Returns all base64 encoded images for a specific page of a job
      parameters:
      - description: Job name
        in: query
        name: job
        required: true
        type: string
      - description: Dataset name
        in: query
        name: dataset
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get base64image by page index
      tags:
      - images
  /api/getImageSet:
    get:
      description: Returns image names and paths for a specific page of a job
      parameters:
      - description: Job name
        in: query
        name: job
        required: true
        type: string
      - description: Page index
        in: query
        name: pageIndex
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get image by page index
      tags:
      - images
  /api/getJobs:
    get:
      description: Returns a list of all job names
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get all job names
      tags:
      - jobs
  /api/getPendingReview:
    get:
      description: Get all pending review data
      parameters:
      - description: Flatten the result
        in: query
        name: flatten
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema: {}
      summary: Get pending review
      tags:
      - review
  /api/savePendingReview:
    post:
      consumes:
      - application/json
      description: Save pending review data
      parameters:
      - description: Pending review data
        in: body
        name: body
        required: true
        schema: {}
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Save pending review
      tags:
      - review
  /api/setAllPages:
    post:
      consumes:
      - application/json
      description: Sets all page details for a given job
      parameters:
      - description: Job name
        in: query
        name: job
        required: true
        type: string
      - description: List of page details
        in: body
        name: pages
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Set all pages for a job
      tags:
      - pages
swagger: "2.0"
